dist: xenial
language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y make sed
install:
  - pip install tox
matrix:
  include:
    - python: "2.7"
      env: TOX_ENVS=py27-django111
    - python: "3.4"
      env: TOX_ENVS=py34-django111,py34-django20
    - python: "3.6"
      env: TOX_ENVS=py36-django111,py36-django20,py36-django21
    - python: "3.7"
      env: TOX_ENVS=py37-django111,py37-django20,py37-django21
    - python: "3.5"
      env: TOX_ENVS=py35-django111,py35-django20,py35-django21
script:
  - tox -e $TOX_ENVS
